### PR TITLE
Tracing fixes

### LINKED ISSUE #322: vhivemetadata must be created by the Invoker
Currently, the metadata , incl. the start timestamp, is created by the first function in an Eventing workflow. We need to do that in the invoker functionality so that Serving and Eventing latencies match apples-to-apples. 

I suggest augmenting the invoker and the 2 microbenchmarks' to use the same helloworld protobuf but with an extra field that is the metadata. gRPC is [backward compatible](https://docs.microsoft.com/en-us/aspnet/core/grpc/versioning?view=aspnetcore-5.0) so adding fields does not break old servers (i.e., the leaf functions in function-images/)

### PR DESCRIPTION
**Pull request by boramalper**
Fixes #322 and #323 (TODO).

### CODE REVIEW

File: utils/benchmarking/eventing/timeseriesdb/main.go [hunk 1]
```diff
@@ -37,7 +37,7 @@ import (
 	"google.golang.org/protobuf/types/known/durationpb"
 	"google.golang.org/protobuf/types/known/timestamppb"
 
-	"eventing/proto"
+	"github.com/ease-lab/vhive/utils/benchmarking/eventing/proto"
```
Comment (ustiugov) [inline utils/benchmarking/eventing/timeseriesdb/main.go:40]: this is correct

File: go.mod [hunk 2]
```diff
@@ -42,6 +42,7 @@ replace (
 
 replace (
 	github.com/ease-lab/vhive/examples/protobuf/helloworld => ./examples/protobuf/helloworld
+	github.com/ease-lab/vhive/utils/benchmarking/eventing => ./utils/benchmarking/eventing
```
[the remark this answers is not in the document]
Comment (boramalper) [reply go.mod:45]: Because it is required in [examples/protobuf/helloworld/helloworld.pb.go](https://github.com/ease-lab/vhive/blob/tracing-fixes/examples/protobuf/helloworld/helloworld.pb.go)

- imported [here](https://github.com/ease-lab/vhive/blob/tracing-fixes/examples/protobuf/helloworld/helloworld.pb.go#L24)
- used [here](https://github.com/ease-lab/vhive/blob/tracing-fixes/examples/protobuf/helloworld/helloworld.pb.go#L45)

[the remark this answers is not in the document]
Comment (ustiugov) [reply go.mod:45]: how did you specify this dependency? is it somehow defined in the protofile or you had to hack it?

**Comment by boramalper** [comment]
Ignored the previous feedback as I started from scratch.

File: function-images/tests/chained-function-serving/go.mod [hunk 3]
```diff
@@ -3,7 +3,7 @@ module tests/chained-functions-serving
 go 1.16
 
 replace (
-	github.com/ease-lab/vhive/utils/tracing/go => ./utils/tracing/go
+	github.com/ease-lab/vhive/utils/tracing/go => ../../../utils/tracing/go
```
Comment (ustiugov) [inline function-images/tests/chained-function-serving/go.mod:6]: this doesn't seem right. how is it going to work when building in a container?

File: function-images/tests/chained-function-serving/producer/producer.go [hunk 4]
```diff
@@ -47,10 +47,18 @@ type producerServer struct {
...
 
-func (ps *producerServer) SayHello(ctx context.Context, req *pb.HelloRequest) (*pb.HelloReply, error) {
+var tracingEnabled = os.Getenv("TRACING") != ""
+
+func (ps *producerServer) SayHello(ctx context.Context, req *pb.HelloRequest) (_ *pb.HelloReply, err error) {
 	// establish a connection
 	addr := fmt.Sprintf("%v:%v", ps.consumerAddr, ps.consumerPort)
-	conn, err := tracing.DialGRPCWithUnaryInterceptor(addr, grpc.WithInsecure())
+	var conn *grpc.ClientConn
+	// TODO: shouldn't we also use grpc.WithBlock() ?
```
Comment (ustiugov) [inline function-images/tests/chained-function-serving/producer/producer.go:56]: yes we should use WithBlock

File: utils/benchmarking/eventing/vhivemetadata/vhivemetadata.go [hunk 5]
```diff
@@ -0,0 +1,36 @@
+package vhivemetadata
```
Comment (ustiugov) [inline utils/benchmarking/eventing/vhivemetadata/vhivemetadata.go:1]: copyright

File: examples/invoker/client.go [hunk 6]
```diff
@@ -36,12 +36,13 @@ import (
...
 
 	ctrdlog "github.com/containerd/containerd/log"
-	pb "github.com/ease-lab/vhive/examples/protobuf/helloworld"
+	"github.com/google/uuid"
 	log "github.com/sirupsen/logrus"
 	"google.golang.org/grpc"
 
 	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
 
+	"eventing/vhivemetadata"
```
Comment (ustiugov) [inline examples/invoker/client.go:45]: please use a full path `github.com/...`

File: examples/invoker/client.go [hunk 7]
```diff
@@ -162,35 +169,42 @@ func SayHello(address string) {
...
 
-	_, err = c.SayHello(ctx, &pb.HelloRequest{Name: "faas"})
+	_, err = c.SayHello(ctx, &HelloRequest{
+		Name: "faas",
+		VHiveMetadata: vhivemetadata.MarshalVHiveMetadata(vhivemetadata.VHiveMetadata{
+			WorkflowId: workflowID,
+			InvocationId: uuid.New().String(),
+			InvokedOn: time.Now().UTC(),
+		}),
+	})
```
Comment (ustiugov) [inline examples/invoker/client.go:184]: make an auxiliary function in the vhivemetadata module

File: examples/invoker/helloworld.proto [hunk 8]
```diff
@@ -0,0 +1,22 @@
...
+  rpc SayHello (HelloRequest) returns (HelloReply) {}
+}
+
+// The request message containing the user's name.
+message HelloRequest {
+  string name = 1;
+  bytes vHiveMetadata = 15;
+}
+
+// The response message containing the greetings
```
Comment (ustiugov) [inline examples/invoker/helloworld.proto:19]: remove comments

File: examples/invoker/measure.go [hunk 9]
```diff
@@ -62,6 +75,10 @@ func End() (durations []time.Duration) {
 	lock.Lock()
 	defer lock.Unlock()
 
+	if conn == nil {
```
Comment (ustiugov) [inline examples/invoker/measure.go:78]: unclear, please add a comment

File: function-images/tests/chained-function-eventing/consumer/main.go [hunk 10]
```diff
@@ -28,7 +28,7 @@ import (
 
 	cloudevents "github.com/cloudevents/sdk-go/v2"
 
-	. "eventing/eventschemas"
+	. "chained_function_eventing/eventschemas"
```
Comment (ustiugov) [inline function-images/tests/chained-function-eventing/consumer/main.go:31]: i am not a big fan of such imports... they hurt readability as one cannot distinguish the module-internal code from the code resident in other modules. please avoid

File: function-images/tests/chained-function-eventing/go.mod [hunk 11]
```diff
@@ -1,8 +1,11 @@
-module eventing
+module chained_function_eventing
 
 go 1.16
 
+replace eventing => ../../../utils/benchmarking/eventing
```
Comment (ustiugov) [inline function-images/tests/chained-function-eventing/go.mod:5]: use a full path

File: function-images/tests/chained-function-eventing/producer/main.go [hunk 12]
```diff
@@ -31,13 +31,12 @@ import (
...
 	"github.com/cloudevents/sdk-go/v2/client"
-	ctrdlog "github.com/containerd/containerd/log"
-	"github.com/google/uuid"
 	"github.com/kelseyhightower/envconfig"
 	"google.golang.org/grpc"
 	"google.golang.org/grpc/reflection"
 
-	. "eventing/eventschemas"
+	. "chained_function_eventing/eventschemas"
+	"eventing/vhivemetadata"
```
Comment (ustiugov) [inline function-images/tests/chained-function-eventing/producer/main.go:39]: use a full path

File: function-images/tests/chained-function-eventing/producer/main.go [hunk 13]
```diff
@@ -31,13 +31,12 @@ import (
...
 	cloudevents "github.com/cloudevents/sdk-go/v2"
 	"github.com/cloudevents/sdk-go/v2/client"
-	ctrdlog "github.com/containerd/containerd/log"
-	"github.com/google/uuid"
 	"github.com/kelseyhightower/envconfig"
 	"google.golang.org/grpc"
 	"google.golang.org/grpc/reflection"
 
-	. "eventing/eventschemas"
+	. "chained_function_eventing/eventschemas"
```
Comment (ustiugov) [inline function-images/tests/chained-function-eventing/producer/main.go:38]: avoid unnamed renaming

File: function-images/tests/chained-function-eventing/producer/main.go [hunk 14]
```diff
@@ -49,25 +48,27 @@ type server struct {
 	UnimplementedGreeterServer
 }
 
-const workflowId = "producer.chained-functions-eventing.192.168.1.240.sslip.io"
+type vHiveMetadata struct {
+	WorkflowId string `json:"WorkflowId"`
+	InvocationId string `json:"InvocationId"`
+	InvokedOn time.Time `json:"InvokedOn"`
+}
```
Comment (ustiugov) [inline function-images/tests/chained-function-eventing/producer/main.go:55]: this should be inside the metadata module. the function's user code should not know about it.

File: function-images/tests/chained-function-eventing/producer/main.go [hunk 15]
```diff
@@ -105,8 +106,7 @@ func main() {
 	defer lis.Close()
 
 	var server server
-	var opts []grpc.ServerOption
-	grpcServer := grpc.NewServer(opts...)
+	grpcServer := grpc.NewServer()
```
Comment (ustiugov) [inline function-images/tests/chained-function-eventing/producer/main.go:109]: please add TODO: add tracing support and a link to the Issue (create one if there is none now)

File: function-images/tests/chained-function-serving/consumer/consumer.go [hunk 16]
```diff
@@ -42,13 +43,17 @@ type consumerServer struct {
 	pb.UnimplementedProducerConsumerServer
 }
 
+var tracingEnabled = os.Getenv("TRACING") != ""
```
Comment (ustiugov) [inline function-images/tests/chained-function-serving/consumer/consumer.go:46]: rename: ENABLE_TRACING

Comment (ustiugov) [reply function-images/tests/chained-function-serving/consumer/consumer.go:46]: make the values to be "true" or "false", opposed to "". Harder to make mistakes

add a call IstracingEnabled() to the tracing module. the tracing module should carefully check the validity of the env var's values (only true and false are valid values, log.Fatal() if invalid)

File: function-images/tests/chained-function-serving/producer/producer.go [hunk 17]
```diff
@@ -47,10 +47,18 @@ type producerServer struct {
...
+	if tracingEnabled {
+		conn, err = tracing.DialGRPCWithUnaryInterceptor(addr, grpc.WithInsecure())
```
Comment (ustiugov) [inline function-images/tests/chained-function-serving/producer/producer.go:58]: WithBlock ?

File: function-images/tests/chained-function-serving/producer/producer.go [hunk 18]
```diff
@@ -47,10 +47,18 @@ type producerServer struct {
...
+	} else {
+		conn, err = grpc.Dial(addr, grpc.WithInsecure())
```
Comment (ustiugov) [inline function-images/tests/chained-function-serving/producer/producer.go:60]: withBlock

File: utils/benchmarking/eventing/vhivemetadata/vhivemetadata.go (hunk 5 above)
Comment (ustiugov) [inline utils/benchmarking/eventing/vhivemetadata/vhivemetadata.go:1]: copyright

**Review by ustiugov — CHANGES_REQUESTED** [review]
- [ ] use a  full path to `utils/benchmarking/eventing` instead of `eventing` when importing
- [ ] update the tracing docs (adding benchmarks?) regarding using of the ENABLE_TRACING env variable
- [ ] IMPORTANT: check that dials in the invoker and the ubenches and everywhere else happen with WithBlock() and WithInsecure. it's a bug.
- [ ] make functions transparent to the vHivemetadata. they should just call into your metadata module with functions like UseTracing(), GetInvocationId() maybe others... Hence, marshal and unmarshal should not be in the function code
- [ ] add a call IstracingEnabled() to the tracing module. the tracing module should carefully check the validity of the env var's values (only true and false are valid values, log.Fatal() if invalid)

File: function-images/tests/chained-function-serving/go.mod (hunk 3 above)
Comment (boramalper) [reply function-images/tests/chained-function-serving/go.mod:6]: I use the whole repo as the build context and selectively copy the directories that I need.

File: docs/benchmarking/adding_benchmarks.md [hunk 19]
```diff
@@ -106,11 +106,32 @@ One can enable tracing by following these steps (example is for Golang):
    ```
 3. If the function is a client, use the instrumented grpc dial method to connect to the server:
    ```go
-   conn, err := tracing.DialGRPCWithUnaryInterceptor(addr, grpc.WithInsecure())
+   conn, err := tracing.DialGRPCWithUnaryInterceptor(addr, grpc.WithBlock(), grpc.WithInsecure())
    ```
-
-The producer in the vHive 
-[serving example](/function-images/tests/chained-function-serving/producer/producer.go) 
+4. To enable tracing instrumentation, set `ENABLE_TRACING` environment variable to
```
Comment (ustiugov) [inline docs/benchmarking/adding_benchmarks.md:111]: add a note that tracing comes with an overhead so end-to-end measurements should be performed with tracing turned off.

File: examples/invoker/measure.go [hunk 20]
```diff
@@ -10,7 +10,8 @@ import (
 	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
 	"google.golang.org/grpc"
 
-	"eventing/proto"
+	"github.com/ease-lab/vhive/utils/benchmarking/eventing/proto"
+
 	"github.com/ease-lab/vhive/examples/endpoint"
 )
```
Comment (ustiugov) [inline examples/invoker/measure.go:17]: please rename `conn` and `client`, indicating that they correspond to the timeseries db service

File: examples/invoker/client.go [hunk 21]
```diff
@@ -138,59 +146,64 @@ func runExperiment(endpoints []Endpoint, runDuration, targetRPS int) (realRPS fl
...
 	defer cancel()
 
-	_, err = c.SayHello(ctx, &pb.HelloRequest{Name: "faas"})
+	_, err = c.SayHello(ctx, &HelloRequest{
+		Name: "faas",
+		VHiveMetadata: vhivemetadata.MakeVHiveMetadata(
+			workflowID,
+			uuid.New().String(),
+			time.Now().UTC(),
+		),
```
Comment (ustiugov) [inline examples/invoker/client.go:182]: offload it to the module

File: utils/benchmarking/eventing/vhivemetadata/vhivemetadata.go [hunk 22]
```diff
@@ -0,0 +1,81 @@
...
+}
+
+func unmarshalVHiveMetadata(d []byte) (vhm vHiveMetadata) {
+	if err := json.Unmarshal(d, &vhm); err != nil {
+		logrus.Fatal("failed to unmarshal vhivemetadata", err)
+	}
+	return
+}
+
+func MakeVHiveMetadata(WorkflowId, InvocationId string, InvokedOn time.Time) []byte {
```
Comment (ustiugov) [inline utils/benchmarking/eventing/vhivemetadata/vhivemetadata.go:58]: use this function in the invoker

**Review by ustiugov — CHANGES_REQUESTED** [review]
minor changes requested

File: docs/benchmarking/adding_benchmarks.md (hunk 19 above)
Comment (ustiugov) [reply docs/benchmarking/adding_benchmarks.md:111]: also do mention the fact that users need to propagate vhivemetadata throughout their proto files

**Review by ustiugov — APPROVED** [review]
